name: frequently-running-task

on:
  schedule:
    # Your cron schedule goes here
    - cron: '0 * * * *'

    run: python python main.py

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        env:
          MY_EMAIL = os.environ.get("MY_EMAIL")
          MY_PASSWORD = os.environ.get("MY_PASSWORD")
          TO_ADDRS = os.environ.get("TO_ADDRS")
        run: python main.py
